[logger]
level = "error"  # Only show error level logs

[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false
headless = true
runOnSave = true

[theme]
primaryColor = "#ff4500"  # Reddit orange
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"
