# Placeholder secrets file to prevent warnings
# Add actual secrets through the Hugging Face Spaces interface

# Reddit API credentials
# REDDIT_CLIENT_ID = ""
# REDDIT_CLIENT_SECRET = ""
# REDDIT_USER_AGENT = "RedditScraperApp/1.0"
